# Generated by Django 4.0.3 on 2022-03-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Pavadink šitą ToDo listą kaip nors originaliai', max_length=100, verbose_name='Pavadinimas')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Ką čia dabar nuveikus', max_length=300, verbose_name='Užduotis')),
                ('isCompleted', models.BooleanField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.todolist')),
            ],
        ),
    ]